### PR TITLE
looked like a typo

### PR DESCRIPTION
**Pull request by skviswa**
Hi @kexinhuang12345 while working on CNN_RNN shape mismatch I noticed this could be a potential typo. Not sure if thats the case but thought it might be worthwhile for you to take a closer look!

### CODE REVIEW

**Comment by kexinhuang12345** [comment]
Yes, you are right Karthik! good catch! Can you remove the .idea/workspace.xml file in the commit? i will then merge this PR

**Comment by skviswa** [comment]
Looks like the workspace.xml wont go away as it is coming from probably forking this repo? Let me see if I can do any workarounds for it

**Comment by skviswa** [comment]
Done!

**Comment by kexinhuang12345** [comment]
Just merged!

**Pull request merged**
