### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by cyrusmaher**
Fix file paths so they don't require running from the deep purpose directory

### CODE REVIEW

**Comment by kexinhuang12345** [comment]
Hey Cyrus, thanks for the PR. looks good, but just to be on the safe side, would this pass for example, this demo? https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/CNN_Transformer_Davis.ipynb? Thanks!

**Comment by cyrusmaher** [comment]
Oops, didn't see this--I need to update my github notification settings. It should work as long as the relative path between utils.py and the data doesn't change. Changing directories in the notebook shouldn't have an effect.

**Comment by kexinhuang12345** [comment]
Cool! One question, what is the `__file__ ` in line 25?

**Comment by kexinhuang12345** [comment]
Great, thanks!

**Pull request merged**
