### PR TITLE
Resolving graph encoding error and some minor improvements

### PR DESCRIPTION
**Pull request by yazdanimehdi**
- If the computer has more than 12GB of ram the graphs will be generated and stored in memory before training.
- resolving issue with dgl.bach() in dgl_collate_func for bad molecules that rdkit returned null in smile_to_graph function
- Using tqdm instead of printing every 100 iterations (better training representation)
- removing redundant data loading for test in DTI

### CODE REVIEW

**Comment by kexinhuang12345** [comment]
Hey Mehdi, thanks so much for the commit! It seems there are lots of edits here. As a sanity check, I will set up tests for DeepPurpose and if it passes all the tests, I will merge them. It will take a week or so. Thanks for the patience!

**Comment by kexinhuang12345** [comment]
Also, i notice you have only made changes to DTI.py, would it also be possible to adapt the same changes to DDI.py, CompoundPred.py, ProteinPred.py, and PPI.py? Just for the sake of consistency.

**Comment by yazdanimehdi** [comment]
Hey,
Sure I will add these changes to other parts.

**Comment by yazdanimehdi** [comment]
Hey,
Sorry for the delay I got busy with other things 
I have added the visual changes in training in all the files you asked for and I fixed the dgl collate function in DDI and CompoundPred as well
I will make a new pull request for them.
Happy Holidays.
Cheers

**Pull request closed without merging**
