### PR TITLE
Creating Visual Changes to Training Process Using tqdm and Fixing Graph-Based Models Issue With Better Memory Managment

### PR DESCRIPTION
**Pull request by yazdanimehdi**

### CODE REVIEW

**Comment by yazdanimehdi** [comment]
@kexinhuang12345 
Hi,
Can you please review the pull request and merge it?
Best,
Mehdi

**Comment by kexinhuang12345** [comment]
Hi Mehdi, thank you for the PR! Did you do any test to see if it works across all the case studies? There are too many changes so i will need to spend some time to read through. It would be great if you could run all of these case studies and see if they work as normal:

https://github.com/kexinhuang12345/DeepPurpose#case-study-1a-a-framework-for-drug-target-interaction-prediction-with-less-than-10-lines-of-codes

**Comment by yazdanimehdi** [comment]
> Hi Mehdi, thank you for the PR! Did you do any test to see if it works across all the case studies? There are too many changes so i will need to spend some time to read through. It would be great if you could run all of these case studies from 1a-e and 2a-b, and see if they work as normal:
> 
> https://github.com/kexinhuang12345/DeepPurpose#case-study-1a-a-framework-for-drug-target-interaction-prediction-with-less-than-10-lines-of-codes
> 
> If you need a processed dataset for c-e, please let me know!

sure but the main version does not work either!

**Comment by kexinhuang12345** [comment]
wait, what does not work? can you give a script?

**Comment by kexinhuang12345** [comment]
I see indeed. The new bindingDB dataset has some big molecule and the MPNN does not support that. I update it to 'CNN' you can test it out. Ideally, it would be great to test DGL based encoding since you made changes on that.

**Pull request closed without merging**
